<?php
require_once(__DIR__ . '/../../config.php');
require_once(__DIR__ . '/lib.php');

$id = required_param('id', PARAM_INT); // course_module id

$cm = get_coursemodule_from_id('pinnwand', $id, 0, false, MUST_EXIST);
$course = get_course($cm->course);
$instance = $DB->get_record('pinnwand', ['id' => $cm->instance], '*', MUST_EXIST);

require_login($course, true, $cm);
$context = context_module::instance($cm->id);
require_capability('mod/pinnwand:view', $context);

$event = \mod_pinnwand\event\course_module_viewed::create([
    'objectid' => $instance->id,
    'context' => $context,
]);
$event->add_record_snapshot('course_modules', $cm);
$event->add_record_snapshot('pinnwand', $instance);
$event->trigger();

$isediting = $PAGE->user_is_editing();
$forceapp = optional_param('app', 0, PARAM_BOOL);
$showapp = !$isediting || $forceapp;

$PAGE->set_url('/mod/pinnwand/view.php', ['id' => $cm->id]);
$PAGE->set_title(format_string($instance->name));
$PAGE->set_heading(format_string($course->fullname));
if ($showapp) {
    // Eigenes, schlankes mobiltaugliches Layout ohne Standard-Moodle-Chrome/Blöcke.
    $PAGE->set_pagelayout('embedded');
} else {
    // Bearbeiten-Modus aktiv: normaler Moodle-View mit Kursnavigation, damit
    // die Aktivitätseinstellungen (Zahnrad/Einstellungsmenü) erreichbar bleiben.
    $PAGE->set_pagelayout('incourse');
}
$PAGE->set_context($context);

$canmanage = has_capability('mod/pinnwand:viewall', $context);

if (!$showapp) {
    echo $OUTPUT->header();
    echo $OUTPUT->heading(format_string($instance->name));
    if ($instance->intro) {
        echo $OUTPUT->box(format_module_intro('pinnwand', $instance, $cm->id), 'generalbox mod_introbox');
    }
    $appurl = new moodle_url('/mod/pinnwand/view.php', ['id' => $cm->id, 'app' => 1]);
    echo $OUTPUT->single_button($appurl, get_string('modulename', 'pinnwand'), 'get');
    if (has_capability('moodle/course:manageactivities', $context)) {
        $settingsurl = new moodle_url('/course/modedit.php', ['update' => $cm->id, 'return' => 1]);
        echo html_writer::div(html_writer::link($settingsurl, get_string('activitysettings', 'pinnwand')), 'mt-2');
    }
    echo $OUTPUT->footer();
    exit;
}

$config = [
    'cmid' => $cm->id,
    'contextid' => $context->id,
    'sesskey' => sesskey(),
    'wwwroot' => $CFG->wwwroot,
    'maxpictures' => (int) $instance->maxpictures,
    'boardpannable' => (bool) $instance->boardpannable,
    'startmode' => ($instance->startmode ?? 'overview') === 'slide' ? 'slide' : 'overview',
    'sidebaropacity' => (int) $instance->sidebaropacity,
    'studentboardclone' => (bool) $instance->studentboardclone,
    'studentboardcreate' => (bool) $instance->studentboardcreate,
    'studentseeotherboards' => (bool) $instance->studentseeotherboards,
    'studentpoststream' => (bool) $instance->studentpoststream,
    'studentlayers' => (bool) $instance->studentlayers,
    'allowconsent' => (bool) $instance->allowconsent,
    'consenttext' => format_string($instance->consenttext),
    'canmanage' => $canmanage,
    'currentuserfullname' => fullname($USER),
    'managerurl' => $canmanage ? (new moodle_url('/mod/pinnwand/manage.php', ['id' => $cm->id]))->out(false) : null,
    'exportpresentationurl' => $canmanage ? (new moodle_url('/mod/pinnwand/export_presentation.php', ['id' => $cm->id]))->out(false) : null,
    'courseurl' => (new moodle_url('/course/view.php', ['id' => $course->id]))->out(false),
    'isediting' => $isediting,
    'settingsurl' => ($isediting && has_capability('moodle/course:manageactivities', $context))
        ? (new moodle_url('/course/modedit.php', ['update' => $cm->id, 'return' => 1]))->out(false) : null,
    'strings' => [
        'step_capture' => get_string('step_capture', 'pinnwand'),
        'step_perspective' => get_string('step_perspective', 'pinnwand'),
        'step_crop' => get_string('step_crop', 'pinnwand'),
        'step_color' => get_string('step_color', 'pinnwand'),
        'step_grid' => get_string('step_grid', 'pinnwand'),
        'step_arrange' => get_string('step_arrange', 'pinnwand'),
        'takephoto' => get_string('takephoto', 'pinnwand'),
        'uploadphoto' => get_string('uploadphoto', 'pinnwand'),
        'addviaurl' => get_string('addviaurl', 'pinnwand'),
        'url_load_error' => get_string('url_load_error', 'pinnwand'),
        'camera_error' => get_string('camera_error', 'pinnwand'),
        'usefullimage' => get_string('usefullimage', 'pinnwand'),
        'rotate90' => get_string('rotate90', 'pinnwand'),
        'mirror' => get_string('mirror', 'pinnwand'),
        'overlay_onboard' => get_string('overlay_onboard', 'pinnwand'),
        'back_course' => get_string('back_course', 'pinnwand'),
        'fullscreen' => get_string('fullscreen', 'pinnwand'),
        'exitfullscreen' => get_string('exitfullscreen', 'pinnwand'),
        'mygallery' => get_string('mygallery', 'pinnwand'),
        'editphoto' => get_string('editphoto', 'pinnwand'),
        'activitysettings' => get_string('activitysettings', 'pinnwand'),
        'retake' => get_string('retake', 'pinnwand'),
        'next' => get_string('next', 'pinnwand'),
        'back' => get_string('back', 'pinnwand'),
        'reset' => get_string('reset', 'pinnwand'),
        'savephoto' => get_string('savephoto', 'pinnwand'),
        'finishandarrange' => get_string('finishandarrange', 'pinnwand'),
        'addanother' => get_string('addanother', 'pinnwand'),
        'perspective_hint' => get_string('perspective_hint', 'pinnwand'),
        'crop_hint' => get_string('crop_hint', 'pinnwand'),
        'grid_none' => get_string('grid_none', 'pinnwand'),
        'grid_square' => get_string('grid_square', 'pinnwand'),
        'grid_fixed' => get_string('grid_fixed', 'pinnwand'),
        'gridsize' => get_string('gridsize', 'pinnwand'),
        'gridcount' => get_string('gridcount', 'pinnwand'),
        'gridcolor' => get_string('gridcolor', 'pinnwand'),
        'brightness' => get_string('brightness', 'pinnwand'),
        'contrast' => get_string('contrast', 'pinnwand'),
        'saturation' => get_string('saturation', 'pinnwand'),
        'grayscale' => get_string('grayscale', 'pinnwand'),
        'maxreached' => get_string('maxreached', 'pinnwand'),
        'consent_label' => get_string('consent_label', 'pinnwand'),
        'gallery_title' => get_string('gallery_title', 'pinnwand'),
        'deletephoto' => get_string('deletephoto', 'pinnwand'),
        'confirmdelete' => get_string('confirmdelete', 'pinnwand'),
        'confirmdelete_shared' => get_string('confirmdelete_shared', 'pinnwand'),
        'deletephoto_multi_hint' => get_string('deletephoto_multi_hint', 'pinnwand'),
        'objectusage_title' => get_string('objectusage_title', 'pinnwand'),
        'undo' => get_string('undo', 'pinnwand'),
        'redo' => get_string('redo', 'pinnwand'),
        'hideannotations' => get_string('hideannotations', 'pinnwand'),
        'showannotations' => get_string('showannotations', 'pinnwand'),
        'clearannotations' => get_string('clearannotations', 'pinnwand'),
        'clearannotations_confirm' => get_string('clearannotations_confirm', 'pinnwand'),
        'wordart_fonts' => get_string('wordart_fonts', 'pinnwand'),
        'hidemedia' => get_string('hidemedia', 'pinnwand'),
        'photocount' => get_string('photocount', 'pinnwand', ['count' => '{count}', 'max' => '{max}']),
        'photocount_unlimited' => get_string('photocount_unlimited', 'pinnwand', '{count}'),
        'loading' => get_string('loading', 'pinnwand'),
        'error_camera' => get_string('error_camera', 'pinnwand'),
        'error_save' => get_string('error_save', 'pinnwand'),
        'step_source' => get_string('step_source', 'pinnwand'),
        'sourceauthor' => get_string('sourceauthor', 'pinnwand'),
        'sourceyear' => get_string('sourceyear', 'pinnwand'),
        'sourceepoch' => get_string('sourceepoch', 'pinnwand'),
        'sourceplace' => get_string('sourceplace', 'pinnwand'),
        'sourceorigauthor' => get_string('sourceorigauthor', 'pinnwand'),
        'source_hint' => get_string('source_hint', 'pinnwand'),
        'gridtoggle' => get_string('gridtoggle', 'pinnwand'),
        'author_me' => get_string('author_me', 'pinnwand'),
        'draw_toggle' => get_string('draw_toggle', 'pinnwand'),
        'draw_done' => get_string('draw_done', 'pinnwand'),
        'draw_clear' => get_string('draw_clear', 'pinnwand'),
        'draw_pen' => get_string('draw_pen', 'pinnwand'),
        'draw_eraser' => get_string('draw_eraser', 'pinnwand'),
        'zoom_in' => get_string('zoom_in', 'pinnwand'),
        'zoom_out' => get_string('zoom_out', 'pinnwand'),
        'zoom_reset' => get_string('zoom_reset', 'pinnwand'),
        'pantool' => get_string('pantool', 'pinnwand'),
        'zoomin' => get_string('zoomin', 'pinnwand'),
        'zoomout' => get_string('zoomout', 'pinnwand'),
        'zoomtool' => get_string('zoomtool', 'pinnwand'),
        'selection_add' => get_string('selection_add', 'pinnwand'),
        'boxselect' => get_string('boxselect', 'pinnwand'),
        'selection_move' => get_string('selection_move', 'pinnwand'),
        'selection_fit' => get_string('selection_fit', 'pinnwand'),
        'trashbin' => get_string('trashbin', 'pinnwand'),
        'trashbin_empty' => get_string('trashbin_empty', 'pinnwand'),
        'trashbin_placement_label' => get_string('trashbin_placement_label', 'pinnwand'),
        'trashbin_restore' => get_string('trashbin_restore', 'pinnwand'),
        'trashbin_delete_forever' => get_string('trashbin_delete_forever', 'pinnwand'),
        'trashbin_delete_forever_confirm' => get_string('trashbin_delete_forever_confirm', 'pinnwand'),
        'step' => get_string('step', 'pinnwand'),
        'filterbar' => get_string('filterbar', 'pinnwand'),
        'filterbar_placeholder' => get_string('filterbar_placeholder', 'pinnwand'),
        'filterbar_clear' => get_string('filterbar_clear', 'pinnwand'),
        'boardof' => get_string('boardof', 'pinnwand', ['cur' => '{cur}', 'total' => '{total}']),
        'newboard' => get_string('newboard', 'pinnwand'),
        'renameboard' => get_string('renameboard', 'pinnwand'),
        'cloneboard' => get_string('cloneboard', 'pinnwand'),
        'cloneboard_confirm' => get_string('cloneboard_confirm', 'pinnwand'),
        'boardhide' => get_string('boardhide', 'pinnwand'),
        'boardshow' => get_string('boardshow', 'pinnwand'),
        'boardswitcher' => get_string('boardswitcher', 'pinnwand'),
        'boardrename_hint' => get_string('boardrename_hint', 'pinnwand'),
        'boardfull_confirm' => get_string('boardfull_confirm', 'pinnwand'),
        'drawonboard' => get_string('drawonboard', 'pinnwand'),
        'erase' => get_string('erase', 'pinnwand'),
        'thread' => get_string('thread', 'pinnwand'),
        'layers' => get_string('layers', 'pinnwand'),
        'layers_empty' => get_string('layers_empty', 'pinnwand'),
        'newthread' => get_string('newthread', 'pinnwand'),
        'deletethread' => get_string('deletethread', 'pinnwand'),
        'confirmdeletethread' => get_string('confirmdeletethread', 'pinnwand'),
        'addtothread' => get_string('addtothread', 'pinnwand'),
        'addframetothread' => get_string('addframetothread', 'pinnwand'),
        'addoverview' => get_string('addoverview', 'pinnwand'),
        'threadstyle' => get_string('threadstyle', 'pinnwand'),
        'threadwidth' => get_string('threadwidth', 'pinnwand'),
        'removefromthread' => get_string('removefromthread', 'pinnwand'),
        'presentthread' => get_string('presentthread', 'pinnwand'),
        'bgmoves_with_zoom' => get_string('bgmoves_with_zoom', 'pinnwand'),
        'present_smallscreen' => get_string('present_smallscreen', 'pinnwand'),
        'present_overview' => get_string('present_overview', 'pinnwand'),
        'present_frame' => get_string('present_frame', 'pinnwand'),
        'present_hint' => get_string('present_hint', 'pinnwand'),
        'startmode_overview' => get_string('startmode_overview', 'pinnwand'),
        'startmode_slide' => get_string('startmode_slide', 'pinnwand'),
        'slide_bg_hide_before' => get_string('slide_bg_hide_before', 'pinnwand'),
        'startmode' => get_string('startmode', 'pinnwand'),
        'startmode_overview' => get_string('startmode_overview', 'pinnwand'),
        'startmode_slide' => get_string('startmode_slide', 'pinnwand'),
        'ink_tool_shapes' => get_string('ink_tool_shapes', 'pinnwand'),
        'ink_shape_rect' => get_string('ink_shape_rect', 'pinnwand'),
        'ink_shape_ellipse' => get_string('ink_shape_ellipse', 'pinnwand'),
        'ink_shape_line' => get_string('ink_shape_line', 'pinnwand'),
        'ink_shape_poly' => get_string('ink_shape_poly', 'pinnwand'),
        'ink_shape_curve' => get_string('ink_shape_curve', 'pinnwand'),
        'slide_bg_persist' => get_string('slide_bg_persist', 'pinnwand'),
        'slide_exit' => get_string('slide_exit', 'pinnwand'),
        'slide_exit_hint' => get_string('slide_exit_hint', 'pinnwand'),
        'addframe_drag' => get_string('addframe_drag', 'pinnwand'),
        'slide_add' => get_string('slide_add', 'pinnwand'),
        'slide_add_title' => get_string('slide_add_title', 'pinnwand'),
        'slide_add_text' => get_string('slide_add_text', 'pinnwand'),
        'slide_add_list' => get_string('slide_add_list', 'pinnwand'),
        'slide_add_shape' => get_string('slide_add_shape', 'pinnwand'),
        'slide_bg' => get_string('slide_bg', 'pinnwand'),
        'slide_bg_opacity' => get_string('slide_bg_opacity', 'pinnwand'),
        'slide_bg_blur' => get_string('slide_bg_blur', 'pinnwand'),
        'slide_bg_invert' => get_string('slide_bg_invert', 'pinnwand'),
        'slide_linked' => get_string('slide_linked', 'pinnwand'),
        'ink_select_all' => get_string('ink_select_all', 'pinnwand'),
        'cutout_wand' => get_string('cutout_wand', 'pinnwand'),
        'cutout_colorrange' => get_string('cutout_colorrange', 'pinnwand'),
        'cutout_tolerance' => get_string('cutout_tolerance', 'pinnwand'),
        'cutout_wand_remove' => get_string('cutout_wand_remove', 'pinnwand'),
        'cutout_wand_show' => get_string('cutout_wand_show', 'pinnwand'),
        'cutout_wand_hint' => get_string('cutout_wand_hint', 'pinnwand'),
        'frame_edit' => get_string('frame_edit', 'pinnwand'),
        'bg_noimage' => get_string('bg_noimage', 'pinnwand'),
        'bg_upload_short' => get_string('bg_upload_short', 'pinnwand'),
        'blend_mode_short' => get_string('blend_mode_short', 'pinnwand'),
        'bg_pdf' => get_string('bg_pdf', 'pinnwand'),
        'bg_pdf_pages' => get_string('bg_pdf_pages', 'pinnwand'),
        'pdf_title' => get_string('pdf_title', 'pinnwand'),
        'pdf_double' => get_string('pdf_double', 'pinnwand'),
        'pdf_all' => get_string('pdf_all', 'pinnwand'),
        'pdf_none' => get_string('pdf_none', 'pinnwand'),
        'pdf_apply' => get_string('pdf_apply', 'pinnwand'),
        'pdf_loading' => get_string('pdf_loading', 'pinnwand'),
        'pdf_error' => get_string('pdf_error', 'pinnwand'),
        'pdf_rendering' => get_string('pdf_rendering', 'pinnwand'),
        'pdf_page' => get_string('pdf_page', 'pinnwand'),
        'pdf_hint' => get_string('pdf_hint', 'pinnwand'),
        'tfblock_colors' => get_string('tfblock_colors', 'pinnwand'),
        'tfblock_shapes' => get_string('tfblock_shapes', 'pinnwand'),
        'img_tab_rotate' => get_string('img_tab_rotate', 'pinnwand'),
        'img_corners_reset' => get_string('img_corners_reset', 'pinnwand'),
        'tf_move_text' => get_string('tf_move_text', 'pinnwand'),
        'tf_text_width' => get_string('tf_text_width', 'pinnwand'),
        'slide_edit' => get_string('slide_edit', 'pinnwand'),
        'slide_label' => get_string('slide_label', 'pinnwand'),
        'addslide' => get_string('addslide', 'pinnwand'),
        'tfblock_slide' => get_string('tfblock_slide', 'pinnwand'),
        'tfblock_elements' => get_string('tfblock_elements', 'pinnwand'),
        'slide_addtext' => get_string('slide_addtext', 'pinnwand'),
        'slide_anim_hint' => get_string('slide_anim_hint', 'pinnwand'),
        'slide_obj_text' => get_string('slide_obj_text', 'pinnwand'),
        'slide_obj_shape' => get_string('slide_obj_shape', 'pinnwand'),
        'slide_anim_withprev' => get_string('slide_anim_withprev', 'pinnwand'),
        'slide_anim_up' => get_string('slide_anim_up', 'pinnwand'),
        'slide_anim_down' => get_string('slide_anim_down', 'pinnwand'),
        'slide_anim_remove' => get_string('slide_anim_remove', 'pinnwand'),
        'slide_anim_static' => get_string('slide_anim_static', 'pinnwand'),
        'slide_anim_add' => get_string('slide_anim_add', 'pinnwand'),
        'slide_anim_step' => get_string('slide_anim_step', 'pinnwand'),
        'step_cutout' => get_string('step_cutout', 'pinnwand'),
        'cutout_erase' => get_string('cutout_erase', 'pinnwand'),
        'cutout_restore' => get_string('cutout_restore', 'pinnwand'),
        'cutout_rect' => get_string('cutout_rect', 'pinnwand'),
        'cutout_ellipse' => get_string('cutout_ellipse', 'pinnwand'),
        'cutout_size' => get_string('cutout_size', 'pinnwand'),
        'cutout_shape_mode' => get_string('cutout_shape_mode', 'pinnwand'),
        'cutout_keep' => get_string('cutout_keep', 'pinnwand'),
        'cutout_remove' => get_string('cutout_remove', 'pinnwand'),
        'cutout_undo' => get_string('cutout_undo', 'pinnwand'),
        'cutout_reset' => get_string('cutout_reset', 'pinnwand'),
        'cutout_hint' => get_string('cutout_hint', 'pinnwand'),
        'blend_mode' => get_string('blend_mode', 'pinnwand'),
        'blend_normal' => get_string('blend_normal', 'pinnwand'),
        'blend_multiply' => get_string('blend_multiply', 'pinnwand'),
        'blend_difference' => get_string('blend_difference', 'pinnwand'),
        'blend_burn' => get_string('blend_burn', 'pinnwand'),
        'layer_peek' => get_string('layer_peek', 'pinnwand'),
        'layer_peek_off' => get_string('layer_peek_off', 'pinnwand'),
        'ink_tool_pen' => get_string('ink_tool_pen', 'pinnwand'),
        'ink_tool_text' => get_string('ink_tool_text', 'pinnwand'),
        'ink_tool_select' => get_string('ink_tool_select', 'pinnwand'),
        'ink_width' => get_string('ink_width', 'pinnwand'),
        'ink_fontsize' => get_string('ink_fontsize', 'pinnwand'),
        'ink_delete_selection' => get_string('ink_delete_selection', 'pinnwand'),
        'tf_change_shape' => get_string('tf_change_shape', 'pinnwand'),
        'tf_pick_shape' => get_string('tf_pick_shape', 'pinnwand'),
        'tf_shape_padding' => get_string('tf_shape_padding', 'pinnwand'),
        'tf_gradient_radial' => get_string('tf_gradient_radial', 'pinnwand'),
        'present_pen' => get_string('present_pen', 'pinnwand'),
        'present_pen_draw' => get_string('present_pen_draw', 'pinnwand'),
        'present_pen_text' => get_string('present_pen_text', 'pinnwand'),
        'present_pen_erase' => get_string('present_pen_erase', 'pinnwand'),
        'present_pen_size' => get_string('present_pen_size', 'pinnwand'),
        'present_pen_clear' => get_string('present_pen_clear', 'pinnwand'),
        'present_show' => get_string('present_show', 'pinnwand'),
        'present_hide' => get_string('present_hide', 'pinnwand'),
        'export_include_annot' => get_string('export_include_annot', 'pinnwand'),
        'export_include_ink' => get_string('export_include_ink', 'pinnwand'),
        'export_start' => get_string('export_start', 'pinnwand'),
        'present_toggle_ink' => get_string('present_toggle_ink', 'pinnwand'),
        'present_toggle_annot' => get_string('present_toggle_annot', 'pinnwand'),
        'tf_add_shape' => get_string('tf_add_shape', 'pinnwand'),
        'tf_shape_fit_text' => get_string('tf_shape_fit_text', 'pinnwand'),
        'tf_shape_fit_text_short' => get_string('tf_shape_fit_text_short', 'pinnwand'),
        'tf_shape_delete' => get_string('tf_shape_delete', 'pinnwand'),
        'tf_star_points' => get_string('tf_star_points', 'pinnwand'),
        'tf_star_inner' => get_string('tf_star_inner', 'pinnwand'),
        'tf_bubble_style' => get_string('tf_bubble_style', 'pinnwand'),
        'tf_bubble_round' => get_string('tf_bubble_round', 'pinnwand'),
        'tf_bubble_rect' => get_string('tf_bubble_rect', 'pinnwand'),
        'tf_bubble_thought' => get_string('tf_bubble_thought', 'pinnwand'),
        'tf_bubble_tail_angle' => get_string('tf_bubble_tail_angle', 'pinnwand'),
        'tf_bubble_tail_len' => get_string('tf_bubble_tail_len', 'pinnwand'),
        'format_normal' => get_string('format_normal', 'pinnwand'),
        'wordart_roty_short' => get_string('wordart_roty_short', 'pinnwand'),
        'wordart_extrude_short' => get_string('wordart_extrude_short', 'pinnwand'),
        'wordart_rotate_short' => get_string('wordart_rotate_short', 'pinnwand'),
        'wordart_skew_short' => get_string('wordart_skew_short', 'pinnwand'),
        'wordart_scaley_short' => get_string('wordart_scaley_short', 'pinnwand'),
        'wordart_glow_short' => get_string('wordart_glow_short', 'pinnwand'),
        'present_empty' => get_string('present_empty', 'pinnwand'),
        'present_prev' => get_string('present_prev', 'pinnwand'),
        'present_next' => get_string('present_next', 'pinnwand'),
        'exitpresent' => get_string('exitpresent', 'pinnwand'),
        'emptyframe' => get_string('emptyframe', 'pinnwand'),
        'threads_empty' => get_string('threads_empty', 'pinnwand'),
        'thread_all_objects' => get_string('thread_all_objects', 'pinnwand'),
        'filter_all' => get_string('filter_all', 'pinnwand'),
        'filter_in_thread' => get_string('filter_in_thread', 'pinnwand'),
        'filter_out_thread' => get_string('filter_out_thread', 'pinnwand'),
        'thread_objects_empty' => get_string('thread_objects_empty', 'pinnwand'),
        'not_in_presentation' => get_string('not_in_presentation', 'pinnwand'),
        'teacherthread' => get_string('teacherthread', 'pinnwand'),
        'poststream' => get_string('poststream', 'pinnwand'),
        'stream_filter_placeholder' => get_string('stream_filter_placeholder', 'pinnwand'),
        'stream_empty' => get_string('stream_empty', 'pinnwand'),
        'stream_hint' => get_string('stream_hint', 'pinnwand'),
        'stream_pin_hint' => get_string('stream_pin_hint', 'pinnwand'),
        'stream_own_label' => get_string('stream_own_label', 'pinnwand'),
        'addtextframe' => get_string('addtextframe', 'pinnwand'),
        'addwordart' => get_string('addwordart', 'pinnwand'),
        'textframe_title' => get_string('textframe_title', 'pinnwand'),
        'preset_none' => get_string('preset_none', 'pinnwand'),
        'preset_paper' => get_string('preset_paper', 'pinnwand'),
        'preset_dark' => get_string('preset_dark', 'pinnwand'),
        'preset_light' => get_string('preset_light', 'pinnwand'),
        'addtextobject' => get_string('addtextobject', 'pinnwand'),
        'removetextobject' => get_string('removetextobject', 'pinnwand'),
        'fontsize' => get_string('fontsize', 'pinnwand'),
        'format_bold' => get_string('format_bold', 'pinnwand'),
        'format_italic' => get_string('format_italic', 'pinnwand'),
        'format_underline' => get_string('format_underline', 'pinnwand'),
        'format_strike' => get_string('format_strike', 'pinnwand'),
        'format_bullets' => get_string('format_bullets', 'pinnwand'),
        'format_superscript' => get_string('format_superscript', 'pinnwand'),
        'format_subscript' => get_string('format_subscript', 'pinnwand'),
        'format_highlight' => get_string('format_highlight', 'pinnwand'),
        'format_fraction' => get_string('format_fraction', 'pinnwand'),
        'lineheight' => get_string('lineheight', 'pinnwand'),
        'letterspacing' => get_string('letterspacing', 'pinnwand'),
        'fontweight' => get_string('fontweight', 'pinnwand'),
        'tfblock_templates' => get_string('tfblock_templates', 'pinnwand'),
        'tf_shape_bg' => get_string('tf_shape_bg', 'pinnwand'),
        'tf_shape_fg' => get_string('tf_shape_fg', 'pinnwand'),
        'tf_shape_rect' => get_string('tf_shape_rect', 'pinnwand'),
        'tf_shape_rounded' => get_string('tf_shape_rounded', 'pinnwand'),
        'tf_shape_circle' => get_string('tf_shape_circle', 'pinnwand'),
        'tf_shape_ellipse' => get_string('tf_shape_ellipse', 'pinnwand'),
        'tf_shape_none' => get_string('tf_shape_none', 'pinnwand'),
        'tf_shape_star' => get_string('tf_shape_star', 'pinnwand'),
        'tf_shape_ribbon' => get_string('tf_shape_ribbon', 'pinnwand'),
        'tf_shape_badge' => get_string('tf_shape_badge', 'pinnwand'),
        'tf_fill' => get_string('tf_fill', 'pinnwand'),
        'tf_outline' => get_string('tf_outline', 'pinnwand'),
        'tf_effects' => get_string('tf_effects', 'pinnwand'),
        'tf_use_gradient' => get_string('tf_use_gradient', 'pinnwand'),
        'tf_width' => get_string('tf_width', 'pinnwand'),
        'tf_shadow' => get_string('tf_shadow', 'pinnwand'),
        'tf_effect_none' => get_string('tf_effect_none', 'pinnwand'),
        'tf_glow' => get_string('tf_glow', 'pinnwand'),
        'tf_target_text' => get_string('tf_target_text', 'pinnwand'),
        'tf_target_shape' => get_string('tf_target_shape', 'pinnwand'),
        'tf_target_card' => get_string('tf_target_card', 'pinnwand'),
        'tf_send_direct' => get_string('tf_send_direct', 'pinnwand'),
        'export_presentation' => get_string('export_presentation', 'pinnwand'),
        'export_presentation_pickboard' => get_string('export_presentation_pickboard', 'pinnwand'),
        'tf_aspect_locked' => get_string('tf_aspect_locked', 'pinnwand'),
        'tf_aspect_unlocked' => get_string('tf_aspect_unlocked', 'pinnwand'),
        'tf_show_board_bg' => get_string('tf_show_board_bg', 'pinnwand'),
        'tf_panels_collapse' => get_string('tf_panels_collapse', 'pinnwand'),
        'tf_panels_expand' => get_string('tf_panels_expand', 'pinnwand'),
        'tf_debug_svg' => get_string('tf_debug_svg', 'pinnwand'),
        'tf_debug_svg_error' => get_string('tf_debug_svg_error', 'pinnwand'),
        'tf_margin_hint' => get_string('tf_margin_hint', 'pinnwand'),
        'tf_margin_label' => get_string('tf_margin_label', 'pinnwand'),
        'tf_margin_auto' => get_string('tf_margin_auto', 'pinnwand'),
        'tf_margin_apply' => get_string('tf_margin_apply', 'pinnwand'),
        'tf_margin_reset' => get_string('tf_margin_reset', 'pinnwand'),
        'tf_exportbounds_hint' => get_string('tf_exportbounds_hint', 'pinnwand'),
        'tf_choose_font' => get_string('tf_choose_font', 'pinnwand'),
        'tf_no_shape_selected' => get_string('tf_no_shape_selected', 'pinnwand'),
        'tf_shadow_angle' => get_string('tf_shadow_angle', 'pinnwand'),
        'tf_shadow_distance' => get_string('tf_shadow_distance', 'pinnwand'),
        'tf_gradient_angle' => get_string('tf_gradient_angle', 'pinnwand'),
        'tf_gradient_hint' => get_string('tf_gradient_hint', 'pinnwand'),
        'tf_gradient_pick_stop_hint' => get_string('tf_gradient_pick_stop_hint', 'pinnwand'),
        'wordart_3d_title' => get_string('wordart_3d_title', 'pinnwand'),
        'wordart_roty' => get_string('wordart_roty', 'pinnwand'),
        'wordart_extrude' => get_string('wordart_extrude', 'pinnwand'),
        'wordart_extrude_color' => get_string('wordart_extrude_color', 'pinnwand'),
        'wordart_rotate' => get_string('wordart_rotate', 'pinnwand'),
        'wordart_skew' => get_string('wordart_skew', 'pinnwand'),
        'wordart_scaley' => get_string('wordart_scaley', 'pinnwand'),
        'wordart_glow' => get_string('wordart_glow', 'pinnwand'),
        'wordart_sample_word' => get_string('wordart_sample_word', 'pinnwand'),
        'wordart_arc_title' => get_string('wordart_arc_title', 'pinnwand'),
        'wordart_arc_none' => get_string('wordart_arc_none', 'pinnwand'),
        'wordart_arc_up' => get_string('wordart_arc_up', 'pinnwand'),
        'wordart_arc_down' => get_string('wordart_arc_down', 'pinnwand'),
        'wordart_arc_wave' => get_string('wordart_arc_wave', 'pinnwand'),
        'wordart_arc_circle' => get_string('wordart_arc_circle', 'pinnwand'),
        'wordart_arc_amount' => get_string('wordart_arc_amount', 'pinnwand'),
        'wordart_pick_template' => get_string('wordart_pick_template', 'pinnwand'),
        'tf_shape_custom' => get_string('tf_shape_custom', 'pinnwand'),
        'tf_shape_custom_hint' => get_string('tf_shape_custom_hint', 'pinnwand'),
        'align_left' => get_string('align_left', 'pinnwand'),
        'align_center' => get_string('align_center', 'pinnwand'),
        'align_right' => get_string('align_right', 'pinnwand'),
        'align_justify' => get_string('align_justify', 'pinnwand'),
        'tf_recent_colors' => get_string('tf_recent_colors', 'pinnwand'),
        'tf_opacity' => get_string('tf_opacity', 'pinnwand'),
        'tf_group_char' => get_string('tf_group_char', 'pinnwand'),
        'tf_group_para' => get_string('tf_group_para', 'pinnwand'),
        'tf_tab_grid' => get_string('tf_tab_grid', 'pinnwand'),
        'tf_tab_wheel' => get_string('tf_tab_wheel', 'pinnwand'),
        'tf_wrap_front' => get_string('tf_wrap_front', 'pinnwand'),
        'tf_wrap_behind' => get_string('tf_wrap_behind', 'pinnwand'),
        'tf_wrap_around' => get_string('tf_wrap_around', 'pinnwand'),
        'tfblock_fonts' => get_string('tfblock_fonts', 'pinnwand'),
        'tfblock_form' => get_string('tfblock_form', 'pinnwand'),
        'tfblock_formulas' => get_string('tfblock_formulas', 'pinnwand'),
        'textcolor' => get_string('textcolor', 'pinnwand'),
        'textframe_placeholder' => get_string('textframe_placeholder', 'pinnwand'),
        'backside' => get_string('backside', 'pinnwand'),
        'cancel' => get_string('cancel', 'pinnwand'),
        'backside_hint' => get_string('backside_hint', 'pinnwand'),
        'unlinkbackside' => get_string('unlinkbackside', 'pinnwand'),
        'bg_color' => get_string('bg_color', 'pinnwand'),
        'bg_image' => get_string('bg_image', 'pinnwand'),
        'bg_image_class' => get_string('bg_image_class', 'pinnwand'),
        'bg_url' => get_string('bg_url', 'pinnwand'),
        'bg_url_apply' => get_string('bg_url_apply', 'pinnwand'),
        'bg_upload' => get_string('bg_upload', 'pinnwand'),
        'bg_brightness' => get_string('bg_brightness', 'pinnwand'),
        'bg_saturation' => get_string('bg_saturation', 'pinnwand'),
        'bg_fit' => get_string('bg_fit', 'pinnwand'),
        'bg_fit_contain' => get_string('bg_fit_contain', 'pinnwand'),
        'bg_fit_cover' => get_string('bg_fit_cover', 'pinnwand'),
        'bg_softedge' => get_string('bg_softedge', 'pinnwand'),
        'sourcetitle' => get_string('sourcetitle', 'pinnwand'),
        'showdata' => get_string('showdata', 'pinnwand'),
        'hidedata' => get_string('hidedata', 'pinnwand'),
        'databtn' => get_string('databtn', 'pinnwand'),
        'pinboard' => get_string('pinboard', 'pinnwand'),
        'sendtoboard' => get_string('sendtoboard', 'pinnwand'),
        'removefromboard' => get_string('removefromboard', 'pinnwand'),
        'pintooltip' => get_string('pintooltip', 'pinnwand'),
        'unpintooltip' => get_string('unpintooltip', 'pinnwand'),
        'draw_text' => get_string('draw_text', 'pinnwand'),
        'text_placeholder' => get_string('text_placeholder', 'pinnwand'),
        'back_menu' => get_string('back_menu', 'pinnwand'),
        'addphoto' => get_string('addphoto', 'pinnwand'),
        'addobject' => get_string('addobject', 'pinnwand'),
        'category_image' => get_string('category_image', 'pinnwand'),
        'category_text' => get_string('category_text', 'pinnwand'),
        'options' => get_string('options', 'pinnwand'),
        'uploaded_on' => get_string('uploaded_on', 'pinnwand'),
        'moderate_mode' => get_string('moderate_mode', 'pinnwand'),
        'moderate_title' => get_string('moderate_title', 'pinnwand'),
        'moderate_empty' => get_string('moderate_empty', 'pinnwand'),
        'sort_user' => get_string('sort_user', 'pinnwand'),
        'sort_year' => get_string('sort_year', 'pinnwand'),
        'sort_upload' => get_string('sort_upload', 'pinnwand'),
        'student_is_author' => get_string('student_is_author', 'pinnwand'),
        'filter_own' => get_string('filter_own', 'pinnwand'),
        'filter_own_mine' => get_string('filter_own_mine', 'pinnwand'),
        'filter_own_others' => get_string('filter_own_others', 'pinnwand'),
        'filter_board' => get_string('filter_board', 'pinnwand'),
        'filter_board_on' => get_string('filter_board_on', 'pinnwand'),
        'filter_board_off' => get_string('filter_board_off', 'pinnwand'),
        'deletephoto_confirm_other' => get_string('deletephoto_confirm_other', 'pinnwand'),
    ],
];

// Ist Moodles Sprach-Cache noch nicht erneuert (z. B. Dateien aktualisiert,
// aber Caches nicht geleert), liefert get_string für neue Texte "[[schlüssel]]".
// Dann direkt aus der Sprachdatei des Plugins lesen (aktuelle Sprache, sonst
// Englisch), damit die Oberfläche trotzdem lesbar bleibt.
$pinnwandlangfile = function ($lang) {
    $string = [];
    $file = __DIR__ . '/lang/' . clean_param($lang, PARAM_SAFEDIR) . '/pinnwand.php';
    if (is_readable($file)) {
        include($file);
    }
    return $string;
};
$pinnwandlangraw = null;
foreach ($config['strings'] as $skey => $sval) {
    if (is_string($sval) && strpos($sval, '[[') === 0) {
        if ($pinnwandlangraw === null) {
            $pinnwandlangraw = $pinnwandlangfile(current_language()) + $pinnwandlangfile('en');
        }
        if (isset($pinnwandlangraw[$skey])) {
            $config['strings'][$skey] = $pinnwandlangraw[$skey];
        }
    }
}

$PAGE->requires->css(new moodle_url('/mod/pinnwand/styles.css', ['v' => get_config('mod_pinnwand', 'version')]));

echo $OUTPUT->header();
?>
<div id="pinnwand-app" class="pinnwand-app" data-title="<?php echo s(format_string($instance->name)); ?>">
  <noscript><?php echo get_string('modulename', 'pinnwand'); ?> benötigt JavaScript.</noscript>
</div>
<script>
  window.pinnwandConfig = <?php echo json_encode($config); ?>;
</script>
<script src="<?php echo (new moodle_url('/mod/pinnwand/js/presentation-player.js', ['v' => get_config('mod_pinnwand', 'version')]))->out(false); ?>"></script>
<script src="<?php echo (new moodle_url('/mod/pinnwand/js/app.js', ['v' => get_config('mod_pinnwand', 'version')]))->out(false); ?>"></script>
<?php
echo $OUTPUT->footer();
