<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'mod_pinnwand_save_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_photo',
        'description' => 'Speichert ein bearbeitetes Foto (inkl. Raster & Einwilligung)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_photos' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_photos',
        'description' => 'Liefert die eigenen Fotos einer Aktivität',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_update_layout' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_layout',
        'description' => 'Speichert Position/Größe/Rotation eines Fotos auf der Anordnungs-Canvas',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_grid' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_grid',
        'description' => 'Legt das Raster für ein Foto fest (nur in der Galerieansicht)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_source' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_source',
        'description' => 'Bearbeitet die Quellenangaben eines Fotos (eigene oder, mit manage-Recht, fremde)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_delete_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'delete_photo',
        'description' => 'Löscht ein eigenes Foto (mit manage-Recht auch fremde)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_save_annotation' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_annotation',
        'description' => 'Speichert die Zeichen-/Schreib-Ebene eines Fotos',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_board_ink' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_board_ink',
        'description' => 'Lädt die eigenen Stylus-Anmerkungen direkt auf dem Board-Hintergrund',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_save_board_ink' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_board_ink',
        'description' => 'Speichert Stylus-Anmerkungen direkt auf dem Board-Hintergrund',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_object_placements' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_object_placements',
        'description' => 'Lädt die zusätzlichen Board-Platzierungen eigener Objekte für ein Board',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_update_object_placement' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_object_placement',
        'description' => 'Aktualisiert Position/Größe/Rotation einer zusätzlichen Board-Platzierung',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_set_placement_status' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_placement_status',
        'description' => 'Entfernt eine zusätzliche Board-Platzierung (Trashbin) oder stellt sie wieder her',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_board_names' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_board_names',
        'description' => 'Lädt die eigenen, individuellen Board-Titel',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_set_board_name' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_board_name',
        'description' => 'Setzt den individuellen Titel eines Boards',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_clone_board' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'clone_board',
        'description' => 'Klont das eigene Board (alle platzierten Fotos) in ein neues Board',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_save_background' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_background',
        'description' => 'Speichert den Hintergrund der Anordnungs-Leinwand',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_all_photos' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_all_photos',
        'description' => 'Klassenansicht: alle Fotos gruppiert nach Nutzer*in',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_set_photo_hidden' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_photo_hidden',
        'description' => 'Blendet ein einzelnes Foto auf der Pinnwand aus/ein',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_set_annotation_onboard' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_annotation_onboard',
        'description' => 'Steuert, ob die Zeichen-/Schreib-Ebene eines Fotos auch auf der Pinnwand sichtbar ist',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_photo',
        'description' => 'Ersetzt das Bild eines bereits gespeicherten Fotos (erneutes Bearbeiten)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_get_threads' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_threads',
        'description' => 'Liefert den eigenen Roten Faden sowie (lesend) den der Lehrkraft',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_add_thread_item' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'add_thread_item',
        'description' => 'Fügt dem eigenen Roten Faden eine Station (Foto oder Leerrahmen) hinzu',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_remove_thread_item' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'remove_thread_item',
        'description' => 'Entfernt eine Station aus dem eigenen Roten Faden',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_reorder_thread_items' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'reorder_thread_items',
        'description' => 'Speichert die per Drag geänderte Reihenfolge des eigenen Roten Fadens',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_thread_frame' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_thread_frame',
        'description' => 'Speichert Position/Größe eines auf der Pinnwand verschobenen/skalierten Leerrahmens',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_set_frame_label' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_frame_label',
        'description' => 'Benennt einen Leerrahmen um',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_delete_thread' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'delete_thread',
        'description' => 'Löscht den eigenen Roten Faden vollständig',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_set_thread_bgmoves' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_thread_bgmoves',
        'description' => 'Legt fest, ob sich der Hintergrund beim Präsentations-Zoom mitbewegt',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_set_thread_style' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_thread_style',
        'description' => 'Legt Farbe und Dicke der Fadenlinie/Rahmen-Umrandung fest',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_stream_photos' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_stream_photos',
        'description' => 'Post-Stream: eigene noch nicht platzierte Fotos, für die Lehrkraft zusätzlich fremde Einreichungen',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_adopt_photo_to_board' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'adopt_photo_to_board',
        'description' => 'Kopiert ein fremdes Foto aus dem Post-Stream auf das eigene Board',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:viewall',
    ],
    'mod_pinnwand_set_backside' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_backside',
        'description' => 'Verknüpft (oder trennt) die Rückseite eines eigenen Fotos mit einem anderen eigenen Foto',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_toggle_backside' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'toggle_backside',
        'description' => 'Blättert zwischen Vorder- und Rückseite eines Fotos um',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
];
