<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'mod_pinnwand_save_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_photo',
        'description' => 'Speichert ein bearbeitetes Foto (inkl. Raster & Einwilligung)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_photos' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_photos',
        'description' => 'Liefert die eigenen Fotos einer Aktivität',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_update_layout' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_layout',
        'description' => 'Speichert Position/Größe/Rotation eines Fotos auf der Anordnungs-Canvas',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_grid' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_grid',
        'description' => 'Legt das Raster für ein Foto fest (nur in der Galerieansicht)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_source' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_source',
        'description' => 'Bearbeitet die Quellenangaben eines Fotos (eigene oder, mit manage-Recht, fremde)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_delete_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'delete_photo',
        'description' => 'Löscht ein eigenes Foto (mit manage-Recht auch fremde)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_save_annotation' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_annotation',
        'description' => 'Speichert die Zeichen-/Schreib-Ebene eines Fotos',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_save_background' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'save_background',
        'description' => 'Speichert den Hintergrund der Anordnungs-Leinwand',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_get_all_photos' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'get_all_photos',
        'description' => 'Klassenansicht: alle Fotos gruppiert nach Nutzer*in',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_set_photo_hidden' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_photo_hidden',
        'description' => 'Blendet ein einzelnes Foto auf der Pinnwand aus/ein',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
    'mod_pinnwand_set_annotation_onboard' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'set_annotation_onboard',
        'description' => 'Steuert, ob die Zeichen-/Schreib-Ebene eines Fotos auch auf der Pinnwand sichtbar ist',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:submit',
    ],
    'mod_pinnwand_update_photo' => [
        'classname'   => 'mod_pinnwand_external',
        'methodname'  => 'update_photo',
        'description' => 'Ersetzt das Bild eines bereits gespeicherten Fotos (erneutes Bearbeiten)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities' => 'mod/pinnwand:view',
    ],
];
